### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by 440c2b** [HenriMaus/SPLSS#1]
Hey ! It seems that you stole this code from [this](https://github.com/Nikii1118/Web-Programming-/blob/f8b0589252e48ce7ec3105073931ffec95fc7c65/WebICP3/Source/Task-2/rps.js) repository. Remember that copy/pasting code without attributing the original author and applying a license to that code -- that you do not own -- is illegal. Please consider solving this issue.

**Comment by HenriMaus** [comment]
Add comment with the original link
More then cut/paste...
